knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(GOOGLE_CLIENT_ID)%'
            client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
            redirect_route: connect_google_check
            redirect_params: {}
        discord:
            type: discord
            client_id: '%env(DISCORD_CLIENT_ID)%'
            client_secret: '%env(DISCORD_CLIENT_SECRET)%'
            redirect_route: connect_discord_check
            redirect_params: {}
        battlenet:
            type: generic
            provider_class: App\Security\BattleNetProvider
            client_id: '%env(BATTLENET_CLIENT_ID)%'
            client_secret: '%env(BATTLENET_CLIENT_SECRET)%'
            redirect_route: connect_battlenet_check
            redirect_params: {}